# configuration file for dotnet-releaser
[msbuild]
project = "dotnet-lens-mcp.sln"
[nuget]
publish_draft = true # publish draft NuGet package per commit
[github]
user = "phil-scott-78"
repo = "dotnet-lens-mcp"
